### ISSUE TITLE
Licensing / copyright 

### ISSUE THREAD

**Issue by haesleinhuepf** [cat-list/cat-list.github.io#2]
Hi @cat-list folks,

you're maintaining a fantastic resource here in this repository! I was just wondering under which conditions one could reuse the code and data published here. Would you mind adding a LICENSE file? If you're new to licensing and/or wonder which license to use, you can read more in this blob post: https://focalplane.biologists.com/2023/05/06/if-you-license-it-itll-be-harder-to-steal-it-why-we-should-license-our-work/

Thanks!

Best,
Robert

**Comment by osumray** [comment]
Hi Robert,

We've now added an MIT license,

Best wishes,
Otto

**Comment by haesleinhuepf** [comment]
Awesome thanks for the quick response!
